# -*- coding: utf-8 -*-
"""Create manuscript Figure 1 from precomputed Figure1 network results.

Visualization only. This script reads ``figure1/result`` workbooks generated by
the dataset pipelines and writes the six panel images plus the combined paper
figure. It does not read source match workbooks and does not recompute network
statistics.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


FIGURE1_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = Path(__file__).resolve().parent
RESULT_ROOT = FIGURE1_ROOT / "result"
PANEL_OUTPUT_DIR = FIGURE1_ROOT / "panels"
MAIN_OUTPUT_DIR = FIGURE1_ROOT
MAIN_FIGSIZE = (13.6, 13.2)

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from utils.indicator_config import MATCH_INDICATORS
from utils.network_plotting import draw_network_panel, draw_shared_legend, save_single_panel


@dataclass(frozen=True)
class PanelSpec:
    panel: str
    dataset: str
    period: str
    title: str
    correlation_workbook: Path
    edge_workbook: Path
    sheet_name: str
    output_png: str
    node_order: list[str]


def dataset_result_path(dataset: str, filename: str) -> Path:
    return RESULT_ROOT / dataset / filename


PANEL_SPECS = [
    PanelSpec(
        panel="A",
        dataset="ligue1",
        period="before_var",
        title="Ligue 1 before VAR",
        correlation_workbook=dataset_result_path("ligue1", "correlation_matrix.xlsx"),
        edge_workbook=dataset_result_path("ligue1", "edge_list.xlsx"),
        sheet_name="before_var",
        output_png="figure1_panel_A_ligue1_before_var.png",
        node_order=MATCH_INDICATORS,
    ),
    PanelSpec(
        panel="B",
        dataset="ligue1",
        period="after_var",
        title="Ligue 1 after VAR",
        correlation_workbook=dataset_result_path("ligue1", "correlation_matrix.xlsx"),
        edge_workbook=dataset_result_path("ligue1", "edge_list.xlsx"),
        sheet_name="after_var",
        output_png="figure1_panel_B_ligue1_after_var.png",
        node_order=MATCH_INDICATORS,
    ),
    PanelSpec(
        panel="C",
        dataset="euro",
        period="before_var",
        title="EURO before VAR",
        correlation_workbook=dataset_result_path("euro", "correlation_matrix.xlsx"),
        edge_workbook=dataset_result_path("euro", "edge_list.xlsx"),
        sheet_name="before_var",
        output_png="figure1_panel_C_euro_before_var.png",
        node_order=MATCH_INDICATORS,
    ),
    PanelSpec(
        panel="D",
        dataset="euro",
        period="after_var",
        title="EURO after VAR",
        correlation_workbook=dataset_result_path("euro", "correlation_matrix.xlsx"),
        edge_workbook=dataset_result_path("euro", "edge_list.xlsx"),
        sheet_name="after_var",
        output_png="figure1_panel_D_euro_after_var.png",
        node_order=MATCH_INDICATORS,
    ),
    PanelSpec(
        panel="E",
        dataset="worldcup",
        period="before_var",
        title="World Cup before VAR",
        correlation_workbook=dataset_result_path("worldcup", "correlation_matrix.xlsx"),
        edge_workbook=dataset_result_path("worldcup", "edge_list.xlsx"),
        sheet_name="before_var",
        output_png="figure1_panel_E_worldcup_before_var.png",
        node_order=MATCH_INDICATORS,
    ),
    PanelSpec(
        panel="F",
        dataset="worldcup",
        period="after_var",
        title="World Cup after VAR",
        correlation_workbook=dataset_result_path("worldcup", "correlation_matrix.xlsx"),
        edge_workbook=dataset_result_path("worldcup", "edge_list.xlsx"),
        sheet_name="after_var",
        output_png="figure1_panel_F_worldcup_after_var.png",
        node_order=MATCH_INDICATORS,
    ),
]


def save_main_figure() -> Path:
    """Save the combined six-panel manuscript Figure 1."""
    output = MAIN_OUTPUT_DIR / "figure1_main.png"
    fig = plt.figure(figsize=MAIN_FIGSIZE)
    grid = fig.add_gridspec(3, 3, width_ratios=[1, 1, 0.48], wspace=0.12, hspace=0.18)
    axes = [
        fig.add_subplot(grid[0, 0]),
        fig.add_subplot(grid[0, 1]),
        fig.add_subplot(grid[1, 0]),
        fig.add_subplot(grid[1, 1]),
        fig.add_subplot(grid[2, 0]),
        fig.add_subplot(grid[2, 1]),
    ]
    legend_ax = fig.add_subplot(grid[:, 2])
    for ax, spec in zip(axes, PANEL_SPECS):
        draw_network_panel(ax, spec, add_panel_label=True)
    draw_shared_legend(legend_ax)
    fig.savefig(output, dpi=300, bbox_inches="tight", facecolor="white")
    fig.savefig(output.with_suffix(".pdf"), dpi=300, bbox_inches="tight", facecolor="white")
    fig.savefig(output.with_suffix(".eps"), dpi=300, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return output


def main() -> None:
    PANEL_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    MAIN_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for spec in PANEL_SPECS:
        save_single_panel(spec, PANEL_OUTPUT_DIR)
    main_output = save_main_figure()
    print(f"Figure1 panels: {PANEL_OUTPUT_DIR}")
    print(f"Figure1 main: {main_output}")
    print(f"Figure1 main EPS: {main_output.with_suffix('.eps')}")


if __name__ == "__main__":
    main()
